CREATE TABLE IF NOT EXISTS `fa_platform_game` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(120) NOT NULL DEFAULT '',
  `subtitle` varchar(255) NOT NULL DEFAULT '',
  `slug` varchar(120) NOT NULL DEFAULT '',
  `cover` varchar(255) NOT NULL DEFAULT '',
  `carousel` text,
  `intro` text,
  `resource_links` text,
  `repair_profile` text,
  `tags` varchar(255) NOT NULL DEFAULT '',
  `is_member_only` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `status` (`status`),
  KEY `weigh` (`weigh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_page` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `terminal` varchar(30) NOT NULL DEFAULT 'common',
  `page_key` varchar(60) NOT NULL DEFAULT '',
  `title` varchar(120) NOT NULL DEFAULT '',
  `config_json` text,
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `terminal_page_key` (`terminal`,`page_key`),
  KEY `status` (`status`),
  KEY `weigh` (`weigh`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_download_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `channel` varchar(60) NOT NULL DEFAULT '',
  `resource_type` varchar(30) NOT NULL DEFAULT '',
  `resource_name` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'started',
  `device_id` varchar(120) NOT NULL DEFAULT '',
  `client_version` varchar(30) NOT NULL DEFAULT '',
  `meta_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_game` (`user_id`,`game_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_install_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'started',
  `install_path` varchar(255) NOT NULL DEFAULT '',
  `device_id` varchar(120) NOT NULL DEFAULT '',
  `client_version` varchar(30) NOT NULL DEFAULT '',
  `error_code` varchar(60) NOT NULL DEFAULT '',
  `meta_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_game` (`user_id`,`game_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_repair_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `repair_type` varchar(30) NOT NULL DEFAULT 'common',
  `action_key` varchar(120) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'started',
  `device_id` varchar(120) NOT NULL DEFAULT '',
  `client_version` varchar(30) NOT NULL DEFAULT '',
  `error_code` varchar(60) NOT NULL DEFAULT '',
  `meta_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_game` (`user_id`,`game_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_download_channel` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL DEFAULT '',
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `base_url` varchar(255) NOT NULL DEFAULT '',
  `headers_json` text,
  `remark` varchar(255) NOT NULL DEFAULT '',
  `priority` int(10) NOT NULL DEFAULT '0',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `channel_key` (`channel_key`),
  KEY `status` (`status`),
  KEY `priority` (`priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_game_resource` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `resource_type` varchar(30) NOT NULL DEFAULT 'game',
  `name` varchar(120) NOT NULL DEFAULT '',
  `version` varchar(60) NOT NULL DEFAULT '',
  `file_path` varchar(255) NOT NULL DEFAULT '',
  `file_hash` varchar(120) NOT NULL DEFAULT '',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `priority` int(10) NOT NULL DEFAULT '0',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `extra_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `game_type` (`game_id`,`resource_type`),
  KEY `status` (`status`),
  KEY `channel_key` (`channel_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_payment_channel` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL DEFAULT '',
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `app_id` varchar(120) NOT NULL DEFAULT '',
  `merchant_id` varchar(120) NOT NULL DEFAULT '',
  `notify_secret` varchar(120) NOT NULL DEFAULT '',
  `priority` int(10) NOT NULL DEFAULT '0',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `channel_key` (`channel_key`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `idem_key` varchar(80) DEFAULT NULL,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `item_type` varchar(30) NOT NULL DEFAULT 'game',
  `item_name` varchar(120) NOT NULL DEFAULT '',
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `pay_status` varchar(30) NOT NULL DEFAULT 'created',
  `paid_at` bigint(16) DEFAULT NULL,
  `meta_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `order_no` (`order_no`),
  UNIQUE KEY `uniq_user_idem` (`user_id`,`idem_key`),
  KEY `user_status` (`user_id`,`pay_status`),
  KEY `game_id` (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_user_asset` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `asset_type` varchar(30) NOT NULL DEFAULT 'game',
  `asset_name` varchar(120) NOT NULL DEFAULT '',
  `source_order_no` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'active',
  `expiretime` bigint(16) DEFAULT NULL,
  `meta_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_asset` (`user_id`,`game_id`,`asset_type`,`asset_name`),
  KEY `source_order_no` (`source_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_product_offer` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `item_type` varchar(30) NOT NULL DEFAULT 'game',
  `item_name` varchar(120) NOT NULL DEFAULT '',
  `base_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `member_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `level_discount_json` text,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_offer` (`game_id`,`item_type`,`item_name`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_reconcile_task` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `task_no` varchar(40) NOT NULL DEFAULT '',
  `biz_date` varchar(10) NOT NULL DEFAULT '',
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `order_total` int(11) unsigned NOT NULL DEFAULT '0',
  `paid_total` int(11) unsigned NOT NULL DEFAULT '0',
  `mismatch_total` int(11) unsigned NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'done',
  `result_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `task_no` (`task_no`),
  KEY `biz_channel` (`biz_date`,`channel_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_order_alert` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `order_no` varchar(40) NOT NULL DEFAULT '',
  `alert_type` varchar(60) NOT NULL DEFAULT '',
  `level` varchar(20) NOT NULL DEFAULT 'warning',
  `detail` text,
  `status` varchar(30) NOT NULL DEFAULT 'open',
  `workorder_no` varchar(40) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `order_no` (`order_no`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_repair_template` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL DEFAULT '',
  `template_key` varchar(80) NOT NULL DEFAULT '',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `repair_type` varchar(30) NOT NULL DEFAULT 'common',
  `steps_json` text,
  `version` int(10) unsigned NOT NULL DEFAULT '1',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `template_key` (`template_key`),
  KEY `game_type` (`game_id`,`repair_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_repair_action` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `template_key` varchar(80) NOT NULL DEFAULT '',
  `action_key` varchar(120) NOT NULL DEFAULT '',
  `repair_type` varchar(30) NOT NULL DEFAULT 'common',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `risk_level` varchar(20) NOT NULL DEFAULT 'low',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_action` (`template_key`,`action_key`,`game_id`),
  KEY `type_status` (`repair_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_version_strategy` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `terminal` varchar(30) NOT NULL DEFAULT 'client',
  `min_version` varchar(30) NOT NULL DEFAULT '',
  `latest_version` varchar(30) NOT NULL DEFAULT '',
  `force_version` varchar(30) NOT NULL DEFAULT '',
  `gray_ratio` int(10) unsigned NOT NULL DEFAULT '0',
  `gray_group_tag` varchar(60) NOT NULL DEFAULT '',
  `switch_json` text,
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `terminal` (`terminal`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_config_release` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `release_no` varchar(40) NOT NULL DEFAULT '',
  `terminal` varchar(30) NOT NULL DEFAULT 'client',
  `release_version` int(10) unsigned NOT NULL DEFAULT '1',
  `status` varchar(30) NOT NULL DEFAULT 'published',
  `snapshot_json` longtext,
  `operator_id` int(11) unsigned NOT NULL DEFAULT '0',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `release_no` (`release_no`),
  KEY `terminal_status` (`terminal`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_material` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL DEFAULT '',
  `material_type` varchar(30) NOT NULL DEFAULT 'image',
  `url` varchar(255) NOT NULL DEFAULT '',
  `thumb` varchar(255) NOT NULL DEFAULT '',
  `size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `mime` varchar(120) NOT NULL DEFAULT '',
  `tags` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `type_status` (`material_type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_message` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `nickname` varchar(80) NOT NULL DEFAULT '',
  `contact` varchar(120) NOT NULL DEFAULT '',
  `content` text,
  `status` varchar(30) NOT NULL DEFAULT 'pending',
  `audit_remark` varchar(255) NOT NULL DEFAULT '',
  `audit_admin_id` int(11) unsigned NOT NULL DEFAULT '0',
  `audit_time` bigint(16) DEFAULT NULL,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status_time` (`status`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_node_health` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `channel_key` varchar(60) NOT NULL DEFAULT '',
  `endpoint` varchar(255) NOT NULL DEFAULT '',
  `latency_ms` int(10) unsigned NOT NULL DEFAULT '0',
  `http_code` int(10) unsigned NOT NULL DEFAULT '0',
  `status` varchar(30) NOT NULL DEFAULT 'ok',
  `detail` varchar(255) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `channel_time` (`channel_key`,`createtime`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_ops_alert` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `alert_type` varchar(60) NOT NULL DEFAULT '',
  `level` varchar(20) NOT NULL DEFAULT 'warning',
  `target` varchar(120) NOT NULL DEFAULT '',
  `detail` text,
  `status` varchar(30) NOT NULL DEFAULT 'open',
  `workorder_no` varchar(40) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `type_status` (`alert_type`,`status`),
  KEY `level` (`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_rollback_task` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `task_no` varchar(40) NOT NULL DEFAULT '',
  `trigger_type` varchar(60) NOT NULL DEFAULT '',
  `terminal` varchar(30) NOT NULL DEFAULT 'client',
  `from_release_no` varchar(40) NOT NULL DEFAULT '',
  `to_release_no` varchar(40) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'done',
  `detail` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `task_no` (`task_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_event_log` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `device_id` varchar(80) NOT NULL DEFAULT '',
  `terminal` varchar(30) NOT NULL DEFAULT 'client',
  `event_name` varchar(80) NOT NULL DEFAULT '',
  `page_key` varchar(60) NOT NULL DEFAULT '',
  `channel` varchar(60) NOT NULL DEFAULT '',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `session_id` varchar(80) NOT NULL DEFAULT '',
  `trace_id` varchar(80) NOT NULL DEFAULT '',
  `props_json` text,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `event_time` (`event_name`,`createtime`),
  KEY `user_time` (`user_id`,`createtime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_user_segment` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL DEFAULT '0',
  `segment_tag` varchar(60) NOT NULL DEFAULT '',
  `score` decimal(10,2) NOT NULL DEFAULT '0.00',
  `active_days_30` int(11) unsigned NOT NULL DEFAULT '0',
  `pay_amount_30` decimal(10,2) NOT NULL DEFAULT '0.00',
  `last_event_time` bigint(16) DEFAULT NULL,
  `snapshot_date` varchar(10) NOT NULL DEFAULT '',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_date` (`user_id`,`snapshot_date`),
  KEY `segment_tag` (`segment_tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_ab_experiment` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `experiment_key` varchar(80) NOT NULL DEFAULT '',
  `name` varchar(120) NOT NULL DEFAULT '',
  `terminal` varchar(30) NOT NULL DEFAULT 'client',
  `status` varchar(30) NOT NULL DEFAULT 'running',
  `targeting_json` text,
  `variants_json` text,
  `metric_event` varchar(80) NOT NULL DEFAULT '',
  `starttime` bigint(16) DEFAULT NULL,
  `endtime` bigint(16) DEFAULT NULL,
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `experiment_key` (`experiment_key`),
  KEY `terminal_status` (`terminal`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_cloud_account` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL DEFAULT '',
  `login_password` varchar(255) NOT NULL DEFAULT '',
  `access_token` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `token_refresh_time` bigint(16) DEFAULT NULL,
  `last_check_time` bigint(16) DEFAULT NULL,
  `last_check_status` varchar(30) NOT NULL DEFAULT '',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `fa_platform_cloud_file` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `remark` varchar(255) NOT NULL DEFAULT '',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT '0',
  `game_id` int(11) unsigned NOT NULL DEFAULT '0',
  `share_code` varchar(80) NOT NULL DEFAULT '',
  `access_code` varchar(30) NOT NULL DEFAULT '',
  `account_rule` varchar(30) NOT NULL DEFAULT 'ordered',
  `account_ids` varchar(255) NOT NULL DEFAULT '',
  `status` varchar(30) NOT NULL DEFAULT 'normal',
  `weigh` int(10) NOT NULL DEFAULT '0',
  `createtime` bigint(16) DEFAULT NULL,
  `updatetime` bigint(16) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `status` (`status`),
  KEY `game_id` (`game_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT IGNORE INTO `fa_auth_rule` (`id`,`type`,`pid`,`name`,`title`,`icon`,`url`,`condition`,`remark`,`ismenu`,`menutype`,`extend`,`py`,`pinyin`,`createtime`,`updatetime`,`weigh`,`status`) VALUES

(890,'file',0,'platformproduct','产品管理','fa fa-cubes','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),68,'normal'),
(891,'file',0,'platformoperate','经营管理','fa fa-briefcase','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),67,'normal'),
(900,'file',0,'platform','平台管理','fa fa-cogs','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),66,'normal'),
(901,'file',890,'platform/game','游戏管理','fa fa-th-large','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),67,'normal'),
(902,'file',900,'platform/page','页面配置','fa fa-window-maximize','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),52,'normal'),
(903,'file',901,'platform/game/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),63,'normal'),
(904,'file',901,'platform/game/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),62,'normal'),
(905,'file',901,'platform/game/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),61,'normal'),
(906,'file',901,'platform/game/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),60,'normal'),
(907,'file',901,'platform/game/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),59,'normal'),
(908,'file',902,'platform/page/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),58,'normal'),
(909,'file',902,'platform/page/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),57,'normal'),
(910,'file',902,'platform/page/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),56,'normal'),
(911,'file',902,'platform/page/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),55,'normal'),
(912,'file',902,'platform/page/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),54,'normal'),
(913,'file',900,'platform/downloadlog','下载日志','fa fa-download','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),47,'normal'),
(914,'file',900,'platform/installlog','安装日志','fa fa-hdd-o','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),46,'normal'),
(915,'file',900,'platform/repairlog','修复日志','fa fa-wrench','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),45,'normal'),
(916,'file',913,'platform/downloadlog/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),50,'normal'),
(917,'file',914,'platform/installlog/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),49,'normal'),
(918,'file',915,'platform/repairlog/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),48,'normal'),
(919,'file',891,'platform/overview','平台概览','fa fa-line-chart','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),62,'normal'),
(920,'file',919,'platform/overview/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),47,'normal'),
(921,'file',913,'platform/downloadlog/export','Export','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),46,'normal'),
(922,'file',914,'platform/installlog/export','Export','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),45,'normal'),
(923,'file',915,'platform/repairlog/export','Export','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),44,'normal'),
(924,'file',890,'platform/channel','渠道管理','fa fa-sitemap','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),64,'normal'),
(925,'file',924,'platform/channel/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),42,'normal'),
(926,'file',924,'platform/channel/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),41,'normal'),
(927,'file',924,'platform/channel/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),40,'normal'),
(928,'file',924,'platform/channel/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),39,'normal'),
(929,'file',924,'platform/channel/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),38,'normal'),
(930,'file',890,'platform/resource','资源管理','fa fa-archive','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),66,'normal'),
(931,'file',930,'platform/resource/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),36,'normal'),
(932,'file',930,'platform/resource/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),35,'normal'),
(933,'file',930,'platform/resource/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),34,'normal'),
(934,'file',930,'platform/resource/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),33,'normal'),
(935,'file',930,'platform/resource/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),32,'normal'),
(936,'file',891,'platform/paychannel','支付渠道','fa fa-credit-card','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),61,'normal'),
(937,'file',936,'platform/paychannel/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),30,'normal'),
(938,'file',936,'platform/paychannel/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),29,'normal'),
(939,'file',936,'platform/paychannel/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),28,'normal'),
(940,'file',936,'platform/paychannel/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),27,'normal'),
(941,'file',936,'platform/paychannel/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),26,'normal'),
(942,'file',891,'platform/order','订单管理','fa fa-list-alt','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),60,'normal'),
(943,'file',942,'platform/order/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),24,'normal'),
(944,'file',942,'platform/order/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),23,'normal'),
(945,'file',942,'platform/order/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),22,'normal'),
(946,'file',891,'platform/asset','资产管理','fa fa-database','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),58,'normal'),
(947,'file',946,'platform/asset/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),20,'normal'),
(948,'file',946,'platform/asset/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),19,'normal'),
(949,'file',946,'platform/asset/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),18,'normal'),
(950,'file',891,'platform/offer','优惠活动','fa fa-tags','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),57,'normal'),
(951,'file',950,'platform/offer/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),16,'normal'),
(952,'file',950,'platform/offer/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),15,'normal'),
(953,'file',950,'platform/offer/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),14,'normal'),
(954,'file',950,'platform/offer/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),13,'normal'),
(955,'file',950,'platform/offer/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),12,'normal'),
(956,'file',891,'platform/reconcile','对账管理','fa fa-balance-scale','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),59,'normal'),
(957,'file',956,'platform/reconcile/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),10,'normal'),
(958,'file',956,'platform/reconcile/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),9,'normal'),
(959,'file',956,'platform/reconcile/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),8,'normal'),
(960,'file',956,'platform/reconcile/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),7,'normal'),
(961,'file',891,'platform/orderalert','订单预警','fa fa-bell','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),56,'normal'),
(962,'file',961,'platform/orderalert/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),5,'normal'),
(963,'file',961,'platform/orderalert/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),4,'normal'),
(964,'file',961,'platform/orderalert/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),3,'normal'),
(965,'file',961,'platform/orderalert/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),2,'normal'),
(966,'file',900,'platform/repairtemplate','修复模板','fa fa-cubes','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),49,'normal'),
(967,'file',966,'platform/repairtemplate/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),0,'normal'),
(968,'file',966,'platform/repairtemplate/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-1,'normal'),
(969,'file',966,'platform/repairtemplate/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-2,'normal'),
(970,'file',966,'platform/repairtemplate/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-3,'normal'),
(971,'file',966,'platform/repairtemplate/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-4,'normal'),
(972,'file',900,'platform/repairaction','修复动作','fa fa-shield','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),48,'normal'),
(973,'file',972,'platform/repairaction/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-6,'normal'),
(974,'file',972,'platform/repairaction/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-7,'normal'),
(975,'file',972,'platform/repairaction/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-8,'normal'),
(976,'file',972,'platform/repairaction/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-9,'normal'),
(977,'file',972,'platform/repairaction/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-10,'normal'),
(978,'file',900,'platform/versionstrategy','版本策略','fa fa-rocket','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),51,'normal'),
(979,'file',978,'platform/versionstrategy/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-12,'normal'),
(980,'file',978,'platform/versionstrategy/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-13,'normal'),
(981,'file',978,'platform/versionstrategy/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-14,'normal'),
(982,'file',978,'platform/versionstrategy/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-15,'normal'),
(983,'file',978,'platform/versionstrategy/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-16,'normal'),
(984,'file',900,'platform/configrelease','配置发布','fa fa-history','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),50,'normal'),
(985,'file',984,'platform/configrelease/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-18,'normal'),
(986,'file',984,'platform/configrelease/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-19,'normal'),
(987,'file',984,'platform/configrelease/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-20,'normal'),
(988,'file',984,'platform/configrelease/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-21,'normal'),
(989,'file',984,'platform/configrelease/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-22,'normal'),
(990,'file',890,'platform/material','素材管理','fa fa-photo','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),65,'normal'),
(991,'file',990,'platform/material/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-24,'normal'),
(992,'file',990,'platform/material/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-25,'normal'),
(993,'file',990,'platform/material/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-26,'normal'),
(994,'file',990,'platform/material/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-27,'normal'),
(995,'file',990,'platform/material/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-28,'normal'),
(996,'file',891,'platform/message','消息中心','fa fa-commenting','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),55,'normal'),
(997,'file',996,'platform/message/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-30,'normal'),
(998,'file',996,'platform/message/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-31,'normal'),
(999,'file',996,'platform/message/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-32,'normal'),
(1000,'file',996,'platform/message/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-33,'normal'),
(1001,'file',891,'platform/workbench','运营工作台','fa fa-tachometer','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),63,'normal'),
(1002,'file',1001,'platform/workbench/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-35,'normal'),
(1003,'file',1001,'platform/workbench/summary','统计摘要','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-36,'normal'),
(1004,'file',900,'platform/nodehealth','节点健康','fa fa-heartbeat','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),44,'normal'),
(1005,'file',1004,'platform/nodehealth/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-38,'normal'),
(1006,'file',1004,'platform/nodehealth/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-39,'normal'),
(1007,'file',1004,'platform/nodehealth/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-40,'normal'),
(1008,'file',1004,'platform/nodehealth/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-41,'normal'),
(1009,'file',900,'platform/opsalert','运维告警','fa fa-warning','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),43,'normal'),
(1010,'file',1009,'platform/opsalert/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-43,'normal'),
(1011,'file',1009,'platform/opsalert/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-44,'normal'),
(1012,'file',1009,'platform/opsalert/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-45,'normal'),
(1013,'file',1009,'platform/opsalert/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-46,'normal'),
(1014,'file',900,'platform/rollbacktask','回滚任务','fa fa-undo','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),42,'normal'),
(1015,'file',1014,'platform/rollbacktask/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-48,'normal'),
(1016,'file',1014,'platform/rollbacktask/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-49,'normal'),
(1017,'file',1014,'platform/rollbacktask/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-50,'normal'),
(1018,'file',900,'platform/eventlog','事件日志','fa fa-dot-circle-o','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),41,'normal'),
(1019,'file',1018,'platform/eventlog/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-52,'normal'),
(1020,'file',1018,'platform/eventlog/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-53,'normal'),
(1021,'file',1018,'platform/eventlog/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-54,'normal'),
(1022,'file',891,'platform/usersegment','用户分群','fa fa-users','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),54,'normal'),
(1023,'file',1022,'platform/usersegment/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-56,'normal'),
(1024,'file',1022,'platform/usersegment/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-57,'normal'),
(1025,'file',1022,'platform/usersegment/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-58,'normal'),
(1026,'file',1022,'platform/usersegment/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-59,'normal'),
(1027,'file',1022,'platform/usersegment/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-60,'normal'),
(1028,'file',891,'platform/abexperiment','AB实验','fa fa-random','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),53,'normal'),
(1029,'file',1028,'platform/abexperiment/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-62,'normal'),
(1030,'file',1028,'platform/abexperiment/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-63,'normal'),
(1031,'file',1028,'platform/abexperiment/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-64,'normal'),
(1032,'file',1028,'platform/abexperiment/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-65,'normal'),
(1033,'file',1028,'platform/abexperiment/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-66,'normal'),
(1034,'file',890,'platform/cloud','云盘资源','fa fa-cloud','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),63,'normal'),
(1035,'file',1034,'platform/cloudaccount','天翼云账号','fa fa-user','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),62,'normal'),
(1036,'file',1035,'platform/cloudaccount/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-67,'normal'),
(1037,'file',1035,'platform/cloudaccount/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-68,'normal'),
(1038,'file',1035,'platform/cloudaccount/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-69,'normal'),
(1039,'file',1035,'platform/cloudaccount/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-70,'normal'),
(1040,'file',1035,'platform/cloudaccount/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-71,'normal'),
(1041,'file',1035,'platform/cloudaccount/checktoken','检测Token','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-72,'normal'),
(1042,'file',1035,'platform/cloudaccount/refreshtoken','刷新Token','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-73,'normal'),
(1043,'file',1034,'platform/cloudfile','天翼云文件','fa fa-file','','','',1,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),61,'normal'),
(1044,'file',1043,'platform/cloudfile/index','View','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-74,'normal'),
(1045,'file',1043,'platform/cloudfile/add','Add','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-75,'normal'),
(1046,'file',1043,'platform/cloudfile/edit','Edit','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-76,'normal'),
(1047,'file',1043,'platform/cloudfile/del','Delete','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-77,'normal'),
(1048,'file',1043,'platform/cloudfile/multi','Multi','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-78,'normal'),
(1049,'file',1043,'platform/cloudfile/accountoptions','账号菜单','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-79,'normal'),
(1050,'file',1043,'platform/cloudfile/previewdownload','获取下载地址','fa fa-circle-o','','','',0,NULL,'','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-80,'normal'),
(1051,'file',1034,'platform/resource/direct','直链资源','fa fa-link','platform/resource/index?ref=direct','','',1,'addtabs','','','',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),-81,'normal');

INSERT IGNORE INTO `fa_auth_group` (`id`,`pid`,`name`,`rules`,`createtime`,`updatetime`,`status`) VALUES
(201,1,'平台运维只读组','891,900,913,914,915,916,917,918,919,920,961,962,984,985,1001,1002,1004,1005,1009,1010,1014,1015,1018,1019,1022,1023,1028,1029,1034,1035,1036,1043,1044',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'normal'),

(202,1,'平台风控处理组','891,900,961,962,963,964,965,996,997,998,999,1000,1009,1010,1011,1012,1013,1014,1015,1016,1017',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'normal'),
(203,1,'平台发布组','890,900,902,908,909,910,911,912,924,925,926,927,928,929,930,931,932,933,934,935,978,979,980,981,982,983,984,985,986,987,988,989,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051',UNIX_TIMESTAMP(),UNIX_TIMESTAMP(),'normal');


